//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picc_d.o.o
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleShoppingArticle
    {
        public int ID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> IsPriceNegotiable { get; set; }
        public string ContactPhoneNumber { get; set; }
        public int VehicleID { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
