//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picc_d.o.o
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleShoppingArticles = new HashSet<VehicleShoppingArticle>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public string MakeAndModel { get; set; }
        public double Mileage { get; set; }
        public int YearOfManufacture { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleShoppingArticle> VehicleShoppingArticles { get; set; }
    }
}
